### ISSUE TITLE
Incompatible with Elementor Pro 3.26.1

### ISSUE THREAD

**Issue by wreiske** [themovation/th-widget-pack#220]
After upgrading Elementor, we had to disable the th-widget-pack to get the editor to load. We were getting the spin wheel of death:

<img width="323" alt="Screenshot 2024-12-18 at 3 23 16 PM" src="https://github.com/user-attachments/assets/d4a04114-f8df-4601-8529-e8516ac683b9" />

```
2024/12/18 22:00:00 [error] 2977633#2977633: *3847104 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /removed/www/wp-content/plugins/removed-elementor-main/widgets/provider-map.php on line 70PHP message: PHP Fatal error:  Uncaught Error: Class 'Elementor\Core\Schemes\Typography' not found in /removed/www/wp-content/plugins/th-widget-pack/header-footer/widgets/class-post-title.php:246
Stack trace:
#0 /removed/www/wp-content/plugins/th-widget-pack/header-footer/widgets/class-post-title.php(102): THHF\WidgetsManager\Widgets\Post_Title->register_post_title_style_controls()
#1 /removed/www/wp-content/plugins/elementor/includes/base/controls-stack.php(2386): THHF\WidgetsManager\Widgets\Post_Title->register_controls()
#2 /removed/www/wp-content/plugins/elementor/includes/base/widget-base.php(1050): Elementor\Controls_Stack->init_controls()
#3 /removed/www/wp-content/plugins/elementor/includes/base/controls-stack.php(569): Elementor\Widget_Base->init_controls()
#4 /removed/www/wp-content/plugins/elementor/includes/base/widget-base.php(184): Elementor\Controls_Stack->get_stack()
#5 /removed/www/wp-content/plugins/elem" while reading response header from upstream, client: x, server: removed.com, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "removed.com", referrer: "https://removed.com/wp-admin/post.php?post=6851&action=elementor&swcfpc=1"

```

Need to move to newer APIs like `\Elementor\Group_Control_Typography::TYPOGRAPHY_1,` and control color.

https://developers.elementor.com/docs/editor-controls/group-control-typography/
https://developers.elementor.com/docs/editor-controls/control-color/

**Comment by teaganm** [comment]
Hi, thank you yes we are working on an update to address this which will be released very soon.

In the meantime, please see here for an interim solution: https://themovation.helpscoutdocs.com/article/322-conflict-with-elementor-3-26

**Comment by gitleye** [comment]
Facing the same issue. 
Temporarily rolling back Elemtentor to 3.25.11 is making it load for now. 
thank you for looking into this issue.

**Comment by teaganm** [comment]
Hi, yes the new version has now been released and it should be available as an update directly in your WP admin area.
